### ISSUE TITLE
Renaming the `master` branch to `main`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab-vim#106]
I've just noticed that tests do not run after merging a PR. This is because `main` slipped in when updating to JupyterLab 4.0. As new repositories and most extensions now use `main` branch, would it make sense to migrate over here too to limit confusion?

https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/2078dc0ad8be24225da67cac8bf954a8e31e66fc/.github/workflows/build.yml#L3-L7

CC @ianhi

**Comment by ianhi** [comment]
makes sense to me

**Comment by ianhi** [comment]
done

**Comment by krassowski** [comment]
For reference, instructions to update locally:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by krassowski** [comment]
Thank you!
