### ISSUE TITLE
Please respect Jupyterlab settings for non-blinking cursor 

### ISSUE THREAD

**Issue by gloryVine** [jupyterlab-contrib/jupyterlab-vim#109]
Hi.
The blinking cursor in jupyterlab was an issue in the past, see e.g. [here](https://github.com/jupyter/notebook/issues/1570) and [here](https://github.com/jupyterlab/jupyterlab/issues/10443). This was ultimately resolved by providing the user with the ability to set `cursorBlinkRate` to zero.
This also worked with jupyterlab-vim in the past. However, when I again started using it recently, I noticed that the cursor is now blinking again in all browsers, despite the above setting.
Is there a way to make jupyterlab-vim respect the jupyterlab setting, or is there another way to disable cursor blinking?

**Comment by gloryVine** [comment]
Jupyterlab `4.0.5` and jupyterlab-vim `4.0.3` on macOS Ventura 13.4.

**Comment by firai** [comment]
The fix/feature has been merged upstream. Now we just have to wait for a new release.

**Comment by firai** [comment]
@krassowski What's the right way to update the version of `@replit/codemirror-vim` in the package? Should I just delete `yarn.lock` and let it re-populate, or should `package.json` and `yarn.lock` be edited manually to strictly control the versions of other packages?

**Comment by krassowski** [comment]
I would suggest to
- make a PR bumping `@codemirror/view` in core jupyterlab (this would require bumping across `package.json` files especially in `@jupyterlab/codemirror`)
- bump the required version of `@replit/codemirror-vim`, `@codemirror/view` and `@jupyterlab/codemirror` in `package.json` then run `jlpm` which will refresh the yarn.lock
