### ISSUE TITLE
Visually indicate which text was yanked

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab-contrib/jupyterlab-vim#117]
Is it possible to visually indicate yanked regions with a highlight? I would like the same functionality as [Neovim provides via this setting](https://neovim.io/doc/user/lua.html#vim.highlight), or [vim-highlightedyank](https://github.com/machakann/vim-highlightedyank) provides for base Vim. I find this useful for confirming the yanked region (especially when grabbing a paragraph or targeting a character where it is easy to overlook that there is another of the same character earlier or grab an extra whitespace)

I tried hacking it with a rebind like `map Y v$y` and hoped the visual selection would flicker before it was yanked, but the yank happens instantaneously so the visual selection is not shown. It seems that codemirror's vim does no include the `gs` command or `:sleep` which otherwise could have been incorporated in a shortcut, so I think this might have to happen in the core extension.  

Here is a short demo of what this could look like:
![](https://camo.githubusercontent.com/3fc438b068ede98cf3197fa402e4cd2a669eb8f0c7448f24406870396cd06eaa/687474703a2f2f692e696d6775722e636f6d2f48756c795a366e2e676966)

**Comment by ianhi** [comment]
This would need to be fixed upstream, there seems to be a feature request there: https://github.com/replit/codemirror-vim/issues/121

**Comment by joelostblom** [comment]
Thanks for linking that issue. I followed up with a comment there and I'm closing this one.
