### ISSUE TITLE
vim mode disabled for first cell when code cell extension is installed or for current cell when changing CodeMirror settings

### ISSUE THREAD

**Issue by firai** [jupyterlab-contrib/jupyterlab-vim#123]
## Description

When a code cell extension, such as `jupyterlab-execute-time`, is installed alongside `jupyterlab-vim`, vim mode does not initialize in the first cell, and the user must switch to another cell and back in order to enable vim in the first cell.

Upon triage by @krassowski, changing CodeMirror settings for code cells also causes vim mode to be disabled for the current cell.

## Reproduce

Type 1
1. Install both `jupyterlab-vim` and `jupyterlab-execute-time`
2. Create a new notebook

Type 2
1. Install `jupyterlab-vim` alone
2. Change CodeMirror settings

## Expected behavior

vim mode properly initializes regardless of other extensions

## Context

- Extension versions:
jupyterlab-vim 4.0.3
jupyterlab-execute-time 3.0.1
- Operating System and its version: Windows
- Browser and its version: Latest Firefox and Edge

**Comment by krassowski** [comment]
Would you mind opening an issue over in `jupyterlab-execute-time`?

**Comment by firai** [comment]
Investigated by @krassowski at https://github.com/deshaw/jupyterlab-execute-time/issues/97#issuecomment-1754064252. To be tracked here.

**Comment by firai** [comment]
Seems like this doesn't occur with every CodeMirror extension. When I use `jupyterlab-vim` with [`jupyterlab-indent-guides`](https://github.com/firai/jupyterlab-indent-guides), neither first load nor changing settings for `jupyterlab-indent-guides` from the Settings Editor disables vim mode.

**Comment by firai** [comment]
It seems like the conflict with `jupyterlab-execute-time` has been fixed by https://github.com/deshaw/jupyterlab-execute-time/pull/120.
