### ISSUE TITLE
Supports for JupyterLab 3.x

### ISSUE THREAD

**Issue by huweiATgithub** [jupyterlab-contrib/jupyterlab-vim#125]
## Description

https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/ea557bbe2fd6fd00e8bb8da0356af317080210a6/pyproject.toml#L25
indicates the current version supports only JupyterLab 4.x.

Is 3.x still supported?

**Comment by firai** [comment]
The last version of the extension that supports JL 3.x is version 0.16.0. You can install that version using pip with `pip install jupyterlab-vim==0.16.0`.
