### ISSUE TITLE
Two different "leave" transitions - One from insert to normal and another from normal to jupyter command mode.

### ISSUE THREAD

**Issue by BAlmeidaS** [jupyterlab-contrib/jupyterlab-vim#126]
First of all, thanks a lot for working and enhancing this lib!

I would like to present a new idea to extend the commands available. Is it possible to expand the command `leave-current-mode` to `leave-insert-mode` - that I believe exists already) and "leave-normal-mode`?

It would be awesome if I could bind two different commands:
1 - that leaves insert mode on the cell and goes to normal mode - no matter how many times I press ESC, I will never be sent to jupyter command mode.
2 - Another one that, being on normal mode, sends me to jupyter command mode. Like Shift ESC.

**Comment by BAlmeidaS** [comment]
I am sorry, I just saw that you added an option to control exactly this:

![image](https://github.com/jupyterlab-contrib/jupyterlab-vim/assets/5148153/172525cc-f8cf-4711-94d4-dd02c4491784)

This solved entirely my issue! You guys rock!

**Comment by BAlmeidaS** [comment]
I am sorry, I just saw that you added an option to control exactly this:

![image](https://github.com/jupyterlab-contrib/jupyterlab-vim/assets/5148153/172525cc-f8cf-4711-94d4-dd02c4491784)

This solved entirely my issue! You guys rock!

**Comment by ianhi** [comment]
@BAlmeidaS is there anything in the readme that would have helped you figure this out sooner? Happy to accept a PR improving the documentaiton

**Comment by BAlmeidaS** [comment]
here it is @ianhi: https://github.com/jupyterlab-contrib/jupyterlab-vim/pull/127
