### ISSUE TITLE
Avoid delay when entering edit mode

### ISSUE THREAD

**Issue by nkaretnikov** [jupyterlab-contrib/jupyterlab-vim#129]
I want to enter Jupyter edit mode with `i`, similar to Vim, because `Enter` is hard to reach.

I remapped it like this:

```
        {
            "command": "notebook:enter-edit-mode",
            "keys": [
                // "Enter"
                "I"
            ],
            "selector": ".jp-Notebook:focus",
            "args": {}
        },
```

This works. However, the cell becomes editable only after a significant delay (3 sec?). Enter still works and does so instantly. Also, bindings like `j` work fine. So why is there a delay? Does it clash with some other keybinding and waits for the second character?

**Comment by krassowski** [comment]
Hi @nkaretnikov what JupyterLab and jupyterlab-vim versions are you using?

**Comment by krassowski** [comment]
<kbd>I</kbd>,  <kbd>I</kbd> is mapped to interrupt kernel in notebooks (via `kernelmenu:interrupt` in lab 4.x). Does overriding this shortcut to something else helps?

**Comment by nkaretnikov** [comment]
Tried commenting `I, I` out - didn't work.
JupyterLab - Version 4.0.8.
axlair-jupyterlab-vim - 4.1.0 (installed via plugins menu).

**Comment by krassowski** [comment]
I think commenting it out does not disable the shortcut itself. Changing it to a different one would do.

**Comment by nkaretnikov** [comment]
Tried that as well - same delay.

**Comment by firai** [comment]
Remapping the key binding doesn't disable the default one. This exact remapping was attempted by someone else, leading to https://github.com/jupyterlab/jupyterlab/issues/15038, and this would need to be solved upstream.
