### ISSUE TITLE
Make insert the default mode of Notebook cells. 

### ISSUE THREAD

**Issue by gordonrust** [jupyterlab-contrib/jupyterlab-vim#13]
Presently, when I jump to a notebook cell, I always end up in the normal mode, even if that cell was in insert mode previously. Do you think it is possible to  make the cell remember their states.

**Comment by ianhi** [comment]
This extension works by listening to every time you switch cells and when you do it runs all of the vim initialization code on the cell you've switched to: https://github.com/axelfahy/jupyterlab-vim/blob/c4e43f940ef4be4c961608b6192412d2f3a33d1f/src/index.ts#L61-L64

My guess is that doing this is resetting the mode. I wonder if adding an if statement checking if the cell is already in vim mode, and if so not setting the keymap would prevent this.

**Comment by ianhi** [comment]
Follow up. That is indeed true. You can get the behavior you want if you only set the cell keymap on creation. This is the default in my pr to jupyterlab adding notebook vim to core https://github.com/jupyterlab/jupyterlab/pull/9068 which uses a different method of setting the cells to be vim.

**Comment by gordonrust** [comment]
Awsome !!. Will test it. You just made my morning with this quick reply and solution. :-)

**Comment by gordonrust** [comment]
And how do i check if the cell is already in vim mode?  (I am really new to this !)

**Comment by gordonrust** [comment]
I got ur suggestion working on my end by using a count variable that runs the vim-mode initialistion only if the count is 0.

But now I am unable to move between cells using j-k  in the normal mode (i have to use up-down only.)

Any ideas?

**Comment by ianhi** [comment]
> And how do i check if the cell is already in vim mode?

I think the easiest way will look somethign like this: (untested but I htink this is will wokr)
```typescript
if (editor.getOption('keymap') === 'vim'){
   return
}else {
// whatever is currently done
}
```

> completely unaware of the codemirror api (or even javascript :-))

This was me no so long ago :).

Codemirror vim api here: https://codemirror.net/doc/manual.html#vimapi

**Comment by ianhi** [comment]
> But now I am unable to move between cells using j-k in the normal mode (i have to use up-down only.)

This is after the changes you made? Or is that a bug in the version of the extension you installed?

**Comment by gordonrust** [comment]
> > But now I am unable to move between cells using j-k in the normal mode (i have to use up-down only.)
> 
> This is after the changes you made? Or is that a bug in the version of the extension you installed?

This might be a bug in the version of the extension installed since I have encountered it earlier. Or maybe, in my custom install I also tweak the  Shift+Enter  keybinding to create a new cell in the insert mode.

I add this to the in the "run-select-next-edit"

` if (content.activeCell !== null) {
        let editor = content.activeCell.editor as CodeMirrorEditor;
        current.content.mode = 'edit';
        (CodeMirror as any).Vim.handleKey(editor.editor, 'i');
    }
}` 


Anways. Am just waiting for your PR for the version of this pluging that would be comapatible with jupytelab 3. Thanks a ton

**Comment by gordonrust** [comment]
> > But now I am unable to move between cells using j-k in the normal mode (i have to use up-down only.)
> 
> This is after the changes you made? Or is that a bug in the version of the extension you installed?

I was able to debug the issue with you approach.

Somehow this function which is responsible for motions definign switching between cell using j-k is not called if I do not reinitialise the cell .
(Line 85 ; src/index.ts)
`lvim.defineMotion('moveByLinesOrCell', (cm: any, head: any, motionArgs: any, vim    : any) =>`
`

**Comment by gordonrust** [comment]
> > But now I am unable to move between cells using j-k in the normal mode (i have to use up-down only.)
> 
> This is after the changes you made? Or is that a bug in the version of the extension you installed?

I was able to debug the issue with you approach.

Somehow this function which is responsible for motions defining switching between cell using j-k is not called if I do not reinitialise the cell .
(Line 85 ; src/index.ts)
`lvim.defineMotion('moveByLinesOrCell', (cm: any, head: any, motionArgs: any, vim    : any) =>`
`

**Comment by gordonrust** [comment]
@ianhi 
I was actually able to configure the following behaviour:
 1. If I use mouse click to go to a cell , I land in the insert mode.
 2. If I use j-k to go to a cell, I land in the insert mode.

The way I did this is :
  1. I create an indicator variable whose default value changes when we are about to jump to next cell.
  2. The cell reintializes using either of
  ` (CodeMirror as any).Vim.handleKey(editor.editor, '<Esc>');` or 
` (CodeMirror as any).Vim.handleKey(editor.editor, 'i');` 
 based on the indicator variable.

Something I am perplexed about is that the indicator variable is initialised to default value in the constructor.

If all the cells are different objects of the class VimCell how does the value of the indicator variable propagates when we switch to a different cell??

I can share my code if you want.

Thanks

**Comment by gordonrust** [comment]
So I was able to make the default mode of code-mirror to be insert mode by simply changing
`(CodeMirror as any).Vim.handleKey(editor.editor, '<Esc>')`;
to `(CodeMirror as any).Vim.handleKey(editor.editor, 'i');`
This is to be changed in the src/codemirrorCommands.ts file in the function `modifyCell` .
This works with jupyterlab 3 (3.4.7 o be exact)
