### ISSUE TITLE
remap setting 'jj' to <esc> not working

### ISSUE THREAD

**Issue by OsicKwon** [jupyterlab-contrib/jupyterlab-vim#131]
## Description

Hi,
I wanted to remap in insert mode that pressing 'jj' to '<esc>' to exit insert mode, entering normal mode.
But, it was just typeing '<esc>' in a cell, which was not executed the command(Escaping)

![image](https://github.com/jupyterlab-contrib/jupyterlab-vim/assets/5477324/f0fc7eaa-6d21-496c-88c8-986164ba7f1b)

![image](https://github.com/jupyterlab-contrib/jupyterlab-vim/assets/5477324/11773656-f585-405d-a174-b1fdbe2e1f31)

## Reproduce

1. Go to 'Settings > Notebook Vim > ExtraKeybindings'
2. Enter `jj` in "Keybinding" input box
3. Enter `<esc>` in "The key sequence to execute" input box
4. Select `insert` in "Mode" selection
5. Select `map` in "Map function" selection

## Expected behavior

Change Insert mode to Normal mode

## Context

- JupyterLab version: Version 4.0.9

- Extension version: Version 4.1.0

- Operating System and its version: Arch Linux
- Browser and its version: Firefox 121

**Comment by ianhi** [comment]
This is not well documented (or at all) but codemirror will only recognize `<Esc>` as the escape key. So if you capitalize the `e` then it should work

**Comment by cgjosephlee** [comment]
@ianhi Thanks all your efforts! I would like to send `Cmd+/` in this box (to toggle comment), how do I achieve this?

**Comment by OsicKwon** [comment]
Thank you so much, @ianhi !!

**Comment by OsicKwon** [comment]
It works very well with <Esc>
