### ISSUE TITLE
`gg` and `G` no longer working in `jupyterlab 4.1.0`

### ISSUE THREAD

**Issue by lukashergt** [jupyterlab-contrib/jupyterlab-vim#134]
## Description

After updating from `jupyterlab 4.0.11` to `jupyterlab 4.1.0`, the commands `gg` and `G` to navigate to the top/bottom cell of the notebook in jupyter mode no longer seem to work. Going back to `jupyterlab 4.0.11` both `gg` and `G` work as expected.

Can anybody else confirm this?

## Context

- Python version: 3.12.1
- jupyterlab-vim version: 4.1.0
- Operating System and its version: Linux Manjaro
- Browser and its version: Firefox 122.0-1

**Comment by ianhi** [comment]
I was not able to replicate on:

python : 3.12.1
jupyterlab-vim: 4.1.0
jupyterlab : 4.1.0
firefox: 112 (on linux)


Was this in a totally fresh environment?

**Comment by lukashergt** [comment]
> I was not able to replicate on:
> 
> python : 3.12.1 
> jupyterlab-vim: 4.1.0 
> jupyterlab : 4.1.0 
> firefox: 112 (on linux)

Huh, weird. 

> Was this in a totally fresh environment?

Yes, new virtualenv...

**Comment by lukashergt** [comment]
I tried again with a fresh virtualenv of python version 3.11.5. Same thing, `gg` and `G` work in `jupyterlab==4.0.11`, but do not work in `jupyterlab==4.1.0`...

**Comment by ianhi** [comment]
ahhh sorry i misread the original issue, i thought you were talking about inside of a cell. I agree I see the same

**Comment by ianhi** [comment]
ahhh I suspect we need to update the CSS selectors: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#change-of-notebook-focus-handling-impacting-command-mode-shortcut-selectors

**Comment by krassowski** [comment]
Yes, but JupyterLab 4.1 was supposed to handle the transition by transparent substitution in the background. I must have missed some selectors, sorry :facepalm:

**Comment by krassowski** [comment]
So https://github.com/jupyterlab/jupyterlab/pull/15639 should have caught `.jp-Notebook:focus` usage as in:

https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/fc42ef650142f95aa8f8f5e3b4f82b2fef03a996/schema/plugin.json#L173-L177

**Comment by krassowski** [comment]
Ok, the selector substitution rules are good but only first shortcut gets fixed (for me <kbd>Y</kbd> <kbd>Y</kbd>):

![image](https://github.com/jupyterlab-contrib/jupyterlab-vim/assets/5832902/018df8af-e3a9-4957-8699-4b2b511f1e17)

instead there is a bug in the logic in:

```py
if (
  oldSelector.includes(change.old) &&
  !selectorsAlreadyWarnedAbout.has(oldSelector)
) {
  newSelector = oldSelector.replace(change.old, change.new);
  selectorDeprecationWarnings.add(
    `"${change.old}" was replaced with "${change.new}" in ${change.versionDeprecated} (present in "${oldSelector}")`
  );
  selectorsAlreadyWarnedAbout.add(oldSelector);
}
```

`selectorsAlreadyWarnedAbout` should not be checked in the outer if as it skips subsequent shortcuts. I will open a PR against JupyterLab,

**Comment by krassowski** [comment]
This is getting fixed in:
- https://github.com/jupyterlab/jupyterlab/pull/15762 and
- https://github.com/jupyterlab-contrib/jupyterlab-vim/pull/135

reviews for both pull requests would be greatly appreciated!

**Comment by lukashergt** [comment]
I can confirm that with #135 `gg` and `G` now jump to the top and bottom cell of the notebook, respectively.

However, it seems the view does not jump. For example, if I am at the bottom of the notebook viewing the bottom cell which is currently highlighted, and I then press `gg`, then the highlight vanishes (and presumably jumps to the top cell), but I am still looking at the bottom cell. Only after pressing `j` or `k` or `zz` (at least twice actually...) does the view follow and jump to the selected cell...

**Comment by krassowski** [comment]
Thank you @ianhi for the quick release and @lukashergt for testing. The scroller node has also changed in lab 4.1 (https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#css-class-name-change-in-the-windowedlist-superclass-of-staticnotebook), and instead of using the public API of notebook, this extension was doing scrolling manually:

https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/a6520efded5415c0bdcb4beffab5b77dd3550d51/src/labCommands.ts#L248-L253

I can take a look tomorrow.

**Comment by ianhi** [comment]
ahhh sorry I didn't catch this. I did make a enough cells in my test notebook to trigger scrolling. I will add that to my mental checklist of things to check.

**Comment by lukashergt** [comment]
Wow, completely resolved as far as I can tell, thanks for these quick fixes @krassowski, @ianhi!
