### ISSUE TITLE
Timeout in Keyboard Shortcuts Maps

### ISSUE THREAD

**Issue by caticoa3** [jupyterlab-contrib/jupyterlab-vim#145]
Is it possible to have a two keystroke mapping, e.g. kj for esc have a time out limit between the first and second keystroke? For example if I would like to type a 'k' in insert mode I have to type two consecutive k's ('k' 'k') because the first 'k' is waiting for a second keystroke. 

It would be nice if a time out was set so that the first key stroke...'k' in the above example would time out and a k would be typed when the second keystroke is not entered. 

- Python package version:
 3.12.2 

- Extension version:
jupyterlab_vim  |  4.1.3  |  pyhd8ed1ab_0  |  conda-forge

JupyterLab v4.0.11
 jupyterlab-jupytext v1.4.3 enabled OK (python, jupytext)
@jupyter-notebook/lab-extension v7.0.8 enabled OK
@axlair/jupyterlab_vim v4.1.3 enabled OK (python, jupyterlab_vim)
@jupyter-widgets/jupyterlab-manager v5.0.11 enabled OK (python, jupyterlab_widgets)

- MacOS Monterey 12.7.4

**Comment by firai** [comment]
Thanks for suggesting. I think this would need to be implemented upstream in [replit/codemirror-vim](https://github.com/replit/codemirror-vim), which provides most of the vim functionality for this extension. Can you please file the proposal there?

**Comment by caticoa3** [comment]
Sure thing. Crossposted [to replit/codemirror issues](https://github.com/replit/codemirror-vim/issues/192)

**Comment by caticoa3** [comment]
Closing this. For anyone else running into this issue please see [solution in code mirror thread](https://github.com/replit/codemirror-vim/issues/192#issuecomment-2434384949)
