### ISSUE TITLE
Not working on jupyterlab  version: 4.2.5

### ISSUE THREAD

**Issue by kirubeltadesse** [jupyterlab-contrib/jupyterlab-vim#148]
## Description

Jupyterlab-vim is not working on jupyterlab  version: 4.2.5

## Reproduce

To reproduce the issue you can simple try to install the new jupyterlab version and try to use jupyterlab-vim on it and see if that works.

**Comment by krassowski** [comment]
Works for me:

![works-for-me](https://github.com/user-attachments/assets/c4eeba3c-1400-408e-8cce-cf213c6041bb)

> you can simple try

Why do bug reports like this are always non reproducible? Please follow the issue template :https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

**Comment by kirubeltadesse** [comment]
Thank you, I will close this issue :)
