### ISSUE TITLE
UnicodeDecodeError during installation

### ISSUE THREAD

**Issue by liganega** [jupyterlab-contrib/jupyterlab-vim#16]
I get the following error during installation:

> UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 263: illegal multibyte sequence
> An error occured.
> IndexError: list index out of range

Environment is as follows:
- OS: Windows 10 pro, latest build
- Python: Anaconda 3.8

**Comment by ianhi** [comment]
Hi @liganega are you sitll having this issue? I think this was an issue with jupyterlab itself which should be fixed now.

**Comment by liganega** [comment]
Thank you @ianhi for your kind reply.

Honestly, I don't remember anymore where I had that problem. But I'll let you know when I encounter the same problem again.

**Comment by firai** [comment]
Hi @liganega, I understand that this has been resolved. Please reopen or open a new issue if you're still having this issue.
