### ISSUE TITLE
Vim command binding for 'Insert Cell Above' does not work

### ISSUE THREAD

**Issue by gloryVine** [jupyterlab-contrib/jupyterlab-vim#39]
As written in the title, I can't create a new code cell above via `Ctrl-O, Ctrl-O`. On the other hand, creating a cell below via `Ctrl-O, O` **does** work. I tried both holding the `Ctrl` key down while typing `O` twice, as well as typing `Ctrl-O` twice in a row. 
I tested this in both Opera and Firefox, with the same results. I am on macOS Catalina 10.15.

**Comment by gloryVine** [comment]
Update: For some reason, `Shift-O` creates a new cell above. But this is not what the readme says.

**Comment by lukashergt** [comment]
The `Shift-O` command is correct (and also the vim way of doing it). The README is confusing, you should look under "Jupyter command bindings" (not "Vim command bindings"). There it says to use `Shift-O` to `Insert Cell Above`.
