### ISSUE TITLE
Clear search

### ISSUE THREAD

**Issue by mlucool** [jupyterlab-contrib/jupyterlab-vim#43]
After pressing `/` there is no way to clear a matched search on a cell (unless of course you search for something not there). Can we clear search on entering nothing?

![search](https://user-images.githubusercontent.com/1813603/128759531-c0b6e815-7d5c-4bda-b2bf-e5d4628a6682.gif)

**Comment by ianhi** [comment]
This is actually the same as normal vim bevhior (at least in my terminal installation). The way to clear the search is with `:noh`.

It might be kind of nice to have something like https://github.com/junegunn/vim-slash but that probably belongs as as separate plugin that works with codemirror itself.

**Comment by mlucool** [comment]
Yeah - turns out it was a mapping that maps `/` to clear also. Thoughts on doing something similar here (opt-in)?

**Comment by ianhi** [comment]
It feels like this ought to already be possible with https://github.com/ianhi/jupyterlab-vimrc#jupyterlab-vimrc although it may require some actual coding as in https://discuss.codemirror.net/t/possible-vim-leader-key-work-around/3006/4  as I'm not sure how well `ex` mappings work for the codemirror vim implementation

**Comment by peytondmurray** [comment]
I think this issue can be closed now - somehow I forgot to target this issue in the related PR. Sorry!

**Comment by krassowski** [comment]
Closing as fixed by #74.
