### ISSUE TITLE
Move to jupyterlab-contrib organization?

### ISSUE THREAD

**Issue by ianhi** [jupyterlab-contrib/jupyterlab-vim#44]
@axelfahy what do you think about moving this repo to the jupyerlab contrib organization: https://github.com/jupyterlab-contrib website: https://jupyterlab-contrib.github.io/?

I think the positive would be that there would be even more robustness to maintainer dropoff (currently just you and me) as I believe this would allow a community sustained org to give access to more people to push and publish changes  (which currently only you have the power to grant).

Also cc @fcollonval (who I believe started that org) in case I got any of this description wrong.

**Comment by axelfahy** [comment]
Yes, I think it makes sense to have in under jupyterlab-contrib if it's okay with them. 

Do you know if there is still work in progress to have the extension directly in jupyter-lab?

**Comment by fcollonval** [comment]
Hey thanks for pinging me @ianhi 

@axelfahy yes anyone can request to transfer a project in the organization. The process is described when opening an issue with the following template: https://github.com/jupyterlab-contrib/jupyterlab-contrib.github.io/issues/new?assignees=&labels=transfer&template=transfer-repository-to-this-organization.md&title=

**Comment by axelfahy** [comment]
Transfer to jupyterlab-contrib is done, closing. Thank you @ianhi for proposing this.
