### ISSUE TITLE
Should we keep the auto publication?

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab-contrib/jupyterlab-vim#48]
I am not a big fan of the auto publication feature. We may want to merge multiple PRs before releasing a new feature. And more importantly we may want to control what should be the future version (this is not gonna be a new patch version each time). So I propose to update the current workflow file to react on `workflow_dispatch` (aka manual trigger) with the level of version update we want.

What do you think @axelfahy @ianhi ?

> if we agree I take that opportunity to fix the npm publication too.

**Comment by axelfahy** [comment]
Ok for me, we don't need an auto publication at each merge. A manual trigger or trigger from a tag should be enough.
