### ISSUE TITLE
Change Code/Markdown/Raw Cell mode keybindings

### ISSUE THREAD

**Issue by baggiponte** [jupyterlab-contrib/jupyterlab-vim#54]
## Description

On some OSs, like macOS, `command + 1/2/3` switches tabs on the browser. Going back to `command + M/R/Y` might be more versatile (albeit `Command Y` might open browser history), or even `ctrl-O, M/R/Y`.

**Comment by ianhi** [comment]
This will be fixed by https://github.com/jupyterlab-contrib/jupyterlab-vim/pull/58

althought I htink you can actually add these keybdings already to the keyboard shortcut settings in jlab

**Comment by ktakanopy** [comment]
I'm also having this problem. I can't remove the default shortcut (command + 1, command + 2 and command + 3). How can I remove them?
