### ISSUE TITLE
What types of PR merges should we use?

### ISSUE THREAD

**Issue by ianhi** [jupyterlab-contrib/jupyterlab-vim#59]
Currently only `squash and merge` is enabled. I suspect that this was set by either @fcollonval or @axelfahy ? Curious what the reason is - I would prefer to have the option to either squash or to uss a merge commit  in order preserve individual commits for later clarity. But don't feel super strongly.

![image](https://user-images.githubusercontent.com/10111092/153992329-d08172da-c3c7-451a-aeed-8de5d660ae68.png)

**Comment by fcollonval** [comment]
I activated the other option. I personally recommend merge & squash as the default to minimize history on the main branch and to ease grasping all changes for a new feature or to fix a bug. But it indeed happen by time to time that keeping some intermediate commit makes sense.
