### ISSUE TITLE
build fails with node 17+

### ISSUE THREAD

**Issue by Coleej** [jupyterlab-contrib/jupyterlab-vim#60]
Building against node 17+ fails because of new crypto library. Node throws the error "Error: error:0308010C:digital envelope routines::unsupported".

[Workarounds](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) are either downgrade node or set the environmental variable NODE_OPTIONS="--openssl-legacy-provider" when running build commands.

I'm not familiar with yarn/npm packages or I would add this to the configs where appropriate. Also just wanted let people know about the workarounds without having to Google.

**Comment by ianhi** [comment]
I noticed this too. In general I think there is more success when using one of the nodejs LTS releases (e.g. 14 or 16). When releasing we always use one of those.


@Coleej out of curiosity why were you trying to build this manually?

**Comment by krassowski** [comment]
Closing as we are now testing against Node 18 (v18.17.1 as of today).
