### ISSUE TITLE
Pastes twice

### ISSUE THREAD

**Issue by bcaso** [jupyterlab-contrib/jupyterlab-vim#61]
## Description

`Ctrl+v` or `Shift+Insert` always paste two copies of the same content. Especially pictures copied from other web pages (pictures copied from local files to the clipboard will not be).

**Comment by joelostblom** [comment]
I see this behavior, but only when pasting images as attachements in notebook cells.

**Comment by ianhi** [comment]
Can you confirm that this doesn't happen in an jupyterlab wihtout jupyterlab vim installed?

**Comment by joelostblom** [comment]
Sorry I realized I was running an older version of jupyterlab, I updated to 3.4.1 and cannot reproduce this with jupyterlab_vim 0.15.1 installed so maybe this issue can be closed?

**Comment by firai** [comment]
I understand that this has been resolved. Please reopen or open a new issue if you're still experiencing this issue.
