### ISSUE TITLE
`0.15.0` broken - cannot use 'c' key

### ISSUE THREAD

**Issue by shinypond** [jupyterlab-contrib/jupyterlab-vim#63]
After the latest update, the key 'c' is unavailable when the insert mode of vim.

Is this a bug?

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Python package version:

- Extension version:

- Operating System and its version: 
- Browser and its version: 

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by ianhi** [comment]
Hi @shinypond  thanks for reporting!

> Is this a bug?

If this is happening consistently in `0.15.0` and not in `0.14.5` then it is almost certainly a bug :(. 

Can you please confirm that if you downgrade jlab vim to `0.14.5` in the same environment then `c` works again?

**Comment by ianhi** [comment]
oh boy. It sure it broken. That's really not great. I wish we had tests that could check things like this.

**Comment by shinypond** [comment]
Thanks for your reply!!

I have just installed jlab vim through the jupyter lab extension tab(leftside in the web), without any terminal command such as pip.
Then how can I downgrade jlab vim to 0.14.5? Use pip install?

Anyway, I hope this problem be solved soon...

**Comment by ianhi** [comment]
> I have just installed jlab vim through the jupyter lab extension tab(leftside in the web)

hmm. I don't know much about how to use that. I would in the terminal do the following:

```
jupyter labextension uninstall @axlair/jupyterlab-vim
pip install jupyterlab-vim==0.14.5
```

---

> Anyway, I hope this problem be solved soon...

me too :disappointed: . Looking around I havne't been able to figure out the cause. If other people could put some eyes on it that'd be really helpful! Full diff here: https://github.com/jupyterlab-contrib/jupyterlab-vim/compare/0.14.5...0.15.0

**Comment by ianhi** [comment]
Oh wow - you can't even type the letter `c` I though you just couldn't do things like `ciw`. That's really bad. Worth considering pulling that release off pypi if it's not an obvious fix. I'm going to bed but can try to think more about this tomorrow

**Comment by shinypond** [comment]
Okay. Thanks for your efforts. Have a good night!

**Comment by ianhi** [comment]
I spoke too soon :) I may have i figured it out

**Comment by ianhi** [comment]
now I don't think i can sleep until I at least try this

**Comment by ianhi** [comment]
ok. Thanks again for reporting! 

new version should be published as soon as https://github.com/jupyterlab-contrib/jupyterlab-vim/runs/5520553204?check_suite_focus=true finished (and then conda-forge version a few hours later)

**Comment by ianhi** [comment]
@shinypond if you get a chance could you try out the new version and confirm that it works for you? Now it truly is bedtime for me i think

**Comment by shinypond** [comment]
Everything is now okay!!! Thanks a lot @ianhi  !!

**Comment by wiseyoungbuck** [comment]
Thanks a bunch. Quite excited to have this back.
