### ISSUE TITLE
Defork this repo?

### ISSUE THREAD

**Issue by ianhi** [jupyterlab-contrib/jupyterlab-vim#66]
When you search for `jupyterlab-vim` on either google or github this repo does not show up. (e.g. https://github.com/search?q=jupyterlab-vim) I believe that this is because this repo is a fork. It's important to keep the credit for @jwkvam but I'm concerned about how this hurts discoverability of the extension. Currently it's very easy for people to find a non-working version and not this working one.

I'm not sure about this but thought I'd bring it up and get thoughts from @fcollonval and @axelfahy

**Comment by fcollonval** [comment]
I have no problem breaking the fork link. If you go that road, the process is to contact [GitHub support](https://support.github.com/request/fork?tags=fork) and I would suggest checking the early work of @jwkvam is properly mentioned in the README.

**Comment by axelfahy** [comment]
I don't have any issue with deforking it as well.

**Comment by firai** [comment]
Since further development will be required to port the extension to JLab 4, this might be a good time to defork?

**Comment by krassowski** [comment]
FYI, this fork is now detached, closing.
