### ISSUE TITLE
Spell checking?

### ISSUE THREAD

**Issue by SimonHeybrock** [jupyterlab-contrib/jupyterlab-vim#67]
Hi, and thanks for your work on this awesome plugin!

Is there a way to get spell-checking (especially in markdown cells) to work with `jupyterlab-vim`? I tried `jupyterlab-spellchecker`, but it seems it does not work in combination. `:set spell` is also not successful.

Any other options or solutions?

Thanks,
Simon

**Comment by krassowski** [comment]
@SimonHeybrock as of JupyterLab 4.0 spellchecker and vim extensions (in both versions) work well together:

![Screenshot from 2023-08-03 01-26-29](https://github.com/jupyterlab-contrib/jupyterlab-vim/assets/5832902/58265987-7695-403f-937f-3d509db77ef0)

If there is a specific issue/conflict between the extensions please provide more details.

**Comment by SimonHeybrock** [comment]
Thanks, I think this can be closed then!
