### ISSUE TITLE
blinking cursor color

### ISSUE THREAD

**Issue by GianniGi** [jupyterlab-contrib/jupyterlab-vim#71]
## Is your feature request related to a problem? Please describe.
blinking cursor color is not very nice

## Describe the solution you'd like
change blinking cursor color

**Comment by Jac-Zac** [comment]
Is there any way to do it ? Can I help somehow to add it in case it is not available?

**Comment by krassowski** [comment]
In v4 the cursor colour can be customised via CSS using `--jp-vim-cursor-color` variable. By default it is set to `#7e7`:

https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/2078dc0ad8be24225da67cac8bf954a8e31e66fc/style/base.css#L20-L22
