### ISSUE TITLE
Move cell Down don't work

### ISSUE THREAD

**Issue by Migacz85** [jupyterlab-contrib/jupyterlab-vim#72]
Ctrl-Y | Move Cell Up
Out of the box is working.

Ctrl-E | Move Cell Down
Don't work.

**Comment by Dcosthephalump** [comment]
I have had this problem, but in the reverse. Currently using Ctrl-E in normal mode will move a cell down while using Ctrl-Y will do nothing at all.

**Comment by firai** [comment]
I can't seem to replicate this with the latest JupyterLab 4.0.6 and jupyterlab-vim 4.0.3. Are you still experiencing this issue? If so, can you please list your operating system and version, browser and version, as well as output from `jupyter troubleshoot`?

**Comment by firai** [comment]
I'll close this for now since there wasn't a response. Please reopen with the requested details or open a new issue with additional details if you're still experiencing this issue.
