### ISSUE TITLE
Add :set nrformats support

### ISSUE THREAD

**Issue by xt0r3-Cambridge** [jupyterlab-contrib/jupyterlab-vim#76]
It is great that <C+a> is supported by the plugin, but I often use it to generate a list of subproblems for a task (4a, 4b, ...).

 It would be great if I could somehow add "alpha" to the nrformats variable, like in actual vim using `:set nrformats+=alpha`

Alternatively, supporting :for and :put also work, but that is a lot trickier, I assume.

**Comment by firai** [comment]
jupyterlab-vim derives its vim capabilities from [replit/codemirror-vim](https://github.com/replit/codemirror-vim), and the option you're asking for would need to be implemented upstream. You can file an issue for codemirror-vim here: https://github.com/replit/codemirror-vim/issues.

**Comment by firai** [comment]
As mentioned above, this feature request would need to be implemented upstream in [replit/codemirror-vim](https://github.com/replit/codemirror-vim). Please file an issue for codemirror-vim at https://github.com/replit/codemirror-vim/issues.
