### ISSUE TITLE
Should we detach the fork?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab-contrib/jupyterlab-vim#78]
I just lost quite some time trying to push to #69 to fix up the lint errors before merging. It seems that while the PR author agreed maintainers to modify it:

![Screenshot from 2023-03-12 22-38-02](https://user-images.githubusercontent.com/5832902/224578199-20af3030-50e7-4333-ae7d-2574808d50bb.png)

It looks that github rejects my edits when pushed from local repo. This is strange as I can push via GitHub UI. I believe it is related to this repository being a fork and the PR fork being associated with `jwkvam/jupyterlab-vim` rather than `jupyterlab-contrib/jupyterlab-vim`.

**Comment by firai** [comment]
This was discussed in #66, but it hasn't happened yet for whatever reason

**Comment by krassowski** [comment]
Closing as duplicate of #66.
