### ISSUE TITLE
undo with `u` does not work on jupyterlab 4

### ISSUE THREAD

**Issue by navdeeprana** [jupyterlab-contrib/jupyterlab-vim#89]
Thank you so much for maintaining and porting the extension to jupyterlab 4. I upgraded to the latest versions of both and undo with `u` does not work. `Ctrl-Z` does.

**Comment by lukashergt** [comment]
I can confirm, `u` within a cell does not work.

In "jupyter" mode, you can create a new cell with `o` and undo that with `u`.

**Comment by ianhi** [comment]
maybe related to https://github.com/jupyterlab/jupyterlab/issues/14113

**Comment by ianhi** [comment]
digging deeper still it seems that undo has become a more complicated action in jupyterlab 4. probably to help with the real time collab stuff. It seems as though ctrl-Z isn't handled by codemirror, but rather by jupyterlab. in particular I think it ends up calling this funciton: https://github.com/jupyterlab/jupyterlab/blob/659c6113a97cb906c8b90867a1fe916e628547f2/packages/codemirror/src/editor.ts#L263-L265

so we'll need to end up overriding what `u` does and have it call that funciton somehow

**Comment by krassowski** [comment]
That's doable. I can open a PR on top of #90.

**Comment by krassowski** [comment]
PR is up: https://github.com/jupyterlab-contrib/jupyterlab-vim/pull/92

**Comment by ianhi** [comment]
fix is now released.

`pip install --upgrade jupyterlab-vim`

**Comment by navdeeprana** [comment]
thank you so much for the quick fix
